"""empty message

Revision ID: 70b081b677fe
Revises: 0da27a1523f0
Create Date: 2022-06-06 02:00:01.842018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70b081b677fe'
down_revision = '0da27a1523f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('re_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reply_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['reply_id'], ['reply.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('re_reply')
    # ### end Alembic commands ###
